# Generated by Django 3.1 on 2021-03-10 09:08

from django.db import migrations, models
import users.models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201213_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletefile',
            name='file',
            field=models.FileField(upload_to=users.models.athlete_directory_path, validators=[users.validators.PDFValidator]),
        ),
    ]
