# Generated by Django 3.1 on 2021-03-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210329_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified_2fa',
            field=models.BooleanField(default=False),
        ),
    ]
