# Generated by Django 3.1 on 2021-03-29 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_auto_20210310_1008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RememberMe',
        ),
    ]
